repository:
  description: description of repo
  private: true
  has_issues: true
  has_wiki: false
  has_projects: false
  has_downloads: true
  # This should be changed once the repo has been configured
  default_branch: master
  allow_squash_merge: true
  # If we're squashing commits then this should be set to false
  allow_merge_commit: true
  allow_rebase_merge: false

labels:

  # Build Labels (Do not change)
  - name: Build Passed
    color: 00cc11
  - name: Build Failed
    color: ff2500

  # PR Type Labels (Do not change or add any)
  - name: Build
    color: ffba00
  - name: CI
    color: ffba00
  - name: Docs
    color: ffba00
  - name: Fix
    color: ffba00
  - name: Feature
    color: ffba00
  - name: Style
    color: ffba00
  - name: Refactor
    color: ffba00
  - name: Performance
    color: ffba00
  - name: Test
    color: ffba00

  # Scope Default Labels
  # Do not change the defaults but you can add additional ones, just use the same color
  - name: Scope/Analytics
    color: 00efff
  - name: Scope/Plugin
    color: 00efff
  - name: Scope/Resource
    color: 00efff

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: ['leads']
      required_status_checks: null
      enforce_admins: true
      restrictions: null
  - name: staging
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: ['leads']
      required_status_checks: null
      enforce_admins: true
      restrictions: null
  - name: development
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: ['leads']
      required_status_checks: null
      enforce_admins: true
      restrictions: null


