snopes_development_flow:
  repo_name: test-probot
  base_branch: staging
  config:
    # - require_squashed_commits
    - workflow_light
  types:
    - build
    - ci
    - docs
    - fix
    - feature
    - style
    - refactor
    - performance
    - test
  scopes:
    - component
    - integration
  
