repo_name: test-probot
base_branch: staging
env_branches:
  - staging
# alternatively it can be squashed_commits
workflow: light
types:
  - build
  - ci
  - docs
  - fix
  - feature
  - style
  - refactor
  - performance
  - test
scopes:
  - component
  - integration
