snopes_development_flow:
  repo_name: test-probot
  config:
    - require_squashed_commits
  types:
    - build
    - ci
    - docs
    - fix
    - feature
    - style
    - refactor
    - performance
    - test
  scopes:
    - component
    - integration
  
