ammend_commits: false
branch_to_verify_task_status: master
branch_to_verify_workflow: development
verify_jira_status: true
jira_project_id: WORDPRESS
jira_verified_status: reviewed
scopes:
  - analytics
  - plugin
  - resource
